// packages/svelte/src/App.svelte
<script lang="ts">
  import '@chatbootai/chat';
</script>

<main>
  <nav>ChatBootAI</nav>
  <cba-chat></cba-chat>
</main>

<style>
  nav {
    background: #333;
    color: #fff;
    padding: 16px;
    font-family:
      'Segoe UI',
      -apple-system,
      BlinkMacSystemFont,
      Roboto,
      'Helvetica Neue',
      sans-serif;
    font-size: 1.25rem;
  }
  cba-chat {
    display: block;
    max-width: 1024px;
    margin: 0 auto;
  }
</style>

// packages/vue/src/App.vue
<script setup lang="ts">
import '@chatbootai/chat';
</script>

<template>
  <nav>ChatBootAI</nav>
  <cba-chat></cba-chat>
</template>

<style scoped>
nav {
  background: #333;
  color: #fff;
  padding: 16px;
  font-family:
    'Segoe UI',
    -apple-system,
    BlinkMacSystemFont,
    Roboto,
    'Helvetica Neue',
    sans-serif;
  font-size: 1.25rem;
}
cba-chat {
  display: block;
  max-width: 1024px;
  margin: 0 auto;
}
</style>
